version: '3.8'
services:
  postgres:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  petclinic:
    build:
      context: .
      target: development
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      - postgres

volumes:
  dbdata:
  